services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: study_smart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - USER_SERVICE_PORT=3001
      - DATABASE_URL=postgresql://pg:pg@postgres:5432/study_smart
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=study_smart
      - JWT_SECRET=najlepiej_dlugi_i_losowy

  course-service:
    build: ./services/course-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - user-service
    environment:
      - NODE_ENV=development
      - COURSE_SERVICE_PORT=3002
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=study_smart
      - USER_SERVICE_URL=http://user-service:3001
      - JWT_SECRET=najlepiej_dlugi_i_losowy

  progress-service:
    build: ./services/progress-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - user-service
      - course-service
    environment:
      - NODE_ENV=development
      - PROGRESS_SERVICE_PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/study_smart
      - USER_SERVICE_URL=http://user-service:3001
      - COURSE_SERVICE_URL=http://course-service:3002
      - JWT_SECRET=najlepiej_dlugi_i_losowy

  frontend:
    build:
      context: ./services/frontend
      args:
        - REACT_APP_USER_SERVICE_URL=http://localhost:3001
        - REACT_APP_COURSE_SERVICE_URL=http://localhost:3002
        - REACT_APP_PROGRESS_SERVICE_URL=http://localhost:3003
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - course-service
      - progress-service
    environment:
      - REACT_APP_USER_SERVICE_URL=http://localhost:3001
      - REACT_APP_COURSE_SERVICE_URL=http://localhost:3002
      - REACT_APP_PROGRESS_SERVICE_URL=http://localhost:3003

volumes:
  postgres_data:
  mongodb_data:
